const String STORAGE_LANGUAGE_CODE = 'STORAGE_LANGUAGE_CODE';
const String STORAGE_DEVICE_FIRST_OPEN_KEY = 'STORAGE_DEVICE_FIRST_OPEN_KEY';
const String STORAGE_USER_TOKEN_KEY = 'STORAGE_USER_TOKEN_KEY';
const String STORAGE_USER_PROFILE_KEY = 'STORAGE_USER_PROFILE_KEY';
const String USER_STORAGE_TOKEN_KEY = 'USER_STORAGE_TOKEN_KEY';




